const modeChoices = [
  {
    id: 1,
    disabled: true,
    title: 'Rapid Bus',
    desc: 'Capital Metro’s MetroRapid service is an example of the Rapid Bus mode. Rapid, in this case, means that the bus operates with frequent, 15-minute or less, arrivals. If traffic is congested, however, a rapid bus has limited ways to get out of it. A rapid bus may have a special bus-only lane to pass traffic, like on Guadalupe and Lavaca streets downtown, but those lanes are just a small part of the overall route. Rapid buses must still share those lanes with turning cars. Rapid buses may be able to change signal timing at traffic lights to get a jump start over other vehicles, but this feature is only included at a handful of locations along a route. Even though rapid buses move a lot people, this mode isn’t considered high-capacity transit because it doesn’t operate in its own dedicated lane for most of a route. In short, rapid buses are one step below true Bus Rapid Transit (BRT) service, and BRT is considered high-capacity transit. \n \n MetroRapid is still an important part of Capital Metro’s service fleet though it isn’t considered a mode option for Project Connect’s new corridor investment projects. Instead, MetroRapid will benefit from more priority lanes and intersection improvements as part of Project Connect’s enhancement projects. The MetroRapid system will also be upgraded with new routes and stations as part of Capital Metro’s Connections 2025 plan. ',
    image: 'modes/Rapid_Bus.jpg',
    capitalCostPerVehicle: 700000,
    minCapitalCostPerMile: 700000,
    minMaintenanceCosts: 2500000,
    capacityPerVehicle: 50,
    minAverageSpeed: 15,
    // guidewayChoices: [{
    //   id: 1,
    //   title: 'Mixed with Normal Traffic',
    //   desc: 'This guideway is the least expensive to construct because it requires few changes. This solution is only as fast as the rest of traffic.',
    //   image: 'guideways/Mixed_with_Normal_Traffic.jpg',
    //   costPerRevHour: 60,
    //   averageSpeed: 15,
    //   capitalCostPerMile: 700000,
    //   maintenanceCosts: 2500000,
    // }],
  }, {
    id: 2,
    title: 'Bus Rapid Transit',
    desc: 'Bus routes that operate in either mixed traffic or their own lanes and provide faster service to connect local activity centers.',
    image: 'modes/Bus_Rapid_Transit.jpg',
    capacityPerVehicle: 60,
    frequency: '10 – 30 minutes',
    routeDistance: '5 – 15 miles',
    distanceBetweenStops: '1/2 – 2 miles',
    capitalCostPerVehicle: 700000,
    minCapitalCostPerMile: 2500000,
    minMaintenanceCosts: 2500000,
    minAverageSpeed: 15,
    quote: '"I’m glad it didn’t take very long to build. It would have been better if it was a train though. People ride trains, not buses."',
    guidewayChoices: [{
      id: 1,
      title: 'Mixed with Normal Traffic',
      desc: 'This guideway is the least expensive to construct because it requires few changes. This solution is only as fast as the rest of traffic.',
      image: 'guideways/Mixed_with_Normal_Traffic.jpg',
      costPerRevHour: 60,
      averageSpeed: 15,
      capitalCostPerMile: 2500000,
      maintenanceCosts: 2500000,
      quote: '“It was nice to not have to deal with much construction, but we spent all this money and I’m still stuck in traffic!”',
    }, {
      id: 2,
      title: 'Dedicated Lane',
      desc: 'This guideway converts a lane for cars into a transit-only lane. – A little paint and now your lane is free from traffic!',
      image: 'guideways/Bus_Rapid_Transit_on_Highway.jpg',
      qoute: '“All it took was a little restriping and now we’re flying!  Well, until we run into all these traffic lights that keep slowing us down.”',
      costPerRevHour: 70,
      averageSpeed: 35,
      capitalCostPerMile: 9000000,
      maintenanceCosts: 2500000,
    }],
  }, {
    id: 3,
    title: 'Modern Streetcar',
    desc: 'Electrified rail service that can operate either in mixed traffic or in its own lane. This service is typically used to circulate in dense, urban areas.',
    image: 'modes/Modern_Streetcar.jpg',
    capacityPerVehicle: 90,
    capitalCostPerVehicle: 3500000,
    frequency: '5 – 15 minutes',
    routeDistance: '2 – 5 miles',
    distanceBetweenStops: '1/8 mile – 1/2 mile',
    minCapitalCostPerMile: 15000000,
    minMaintenanceCosts: 25000000,
    minAverageSpeed: 15,
    quote: '“There lots of cool restaurants and shops that have popped up nearby but it’s so slow -- I can walk faster than this thing! I can definitely bike faster than this!"',
    guidewayChoices: [{
      id: 1,
      title: 'Fixed Rail with Mixed Traffic',
      desc: 'This guideway requires building new track in the road. Because cars can still drive in the same lane as the train, the train is only as fast as the rest of traffic.',
      image: 'guideways/Fixed_Rail_with_Mixed_Traffic.jpg',
      costPerRevHour: 180,
      averageSpeed: 15,
      capitalCostPerMile: 15000000,
      maintenanceCosts: 25000000,
      quote: '“I love shopping at cool Austin boutiques, grabbing a cup of fair-trade coffee, then easily hopping on the train just across the street! The drawback is that we spent tons of money on a train -- and it’s still stuck in traffic.”',
    }, {
      id: 2,
      title: 'Fully Dedicated Fixed Railway',
      desc: 'This guideway requires building new track in the road. The train can travel without traffic however, the train will still need to yield to traffic signals along the route.',
      image: 'guideways/Fully_Dedicated_Fixed_Railway.jpg',
      quote: '“The train zips through some of the most congested roads. It took forever to build, though, and now local shop owners nearby complain that the tracks are cutting their customers off.”',
      costPerRevHour: 180,
      averageSpeed: 30,
      capitalCostPerMile: 25000000,
      maintenanceCosts: 25000000,
    }],
  }, {
    id: 4,
    title: 'Light Rail (LRT)',
    desc: 'Electrified rail service that operates in its own lane (or right of way), and connects local activity centers.',
    image: 'modes/Light_Rail.jpg',
    capacityPerVehicle: 110,
    frequency: '10 – 30 minutes',
    routeDistance: '5 – 15 miles',
    distanceBetweenStops: '1/2 – 2 miles',
    capitalCostPerVehicle: 5000000,
    minCapitalCostPerMile: 80000000,
    minMaintenanceCosts: 20000000,
    minAverageSpeed: 30,
    quote: '“I love how many people can ride and how modern – some might say, ‘sexy’ -- it looks, but it took forever to build the thing and cost way too much.”',
    guidewayChoices: [{
      id: 1,
      title: 'Fully Dedicated Fixed Railway',
      desc: 'This guideway requires building new track in the road. Because cars can still drive in the same lane as the train, the train is only as fast as the rest of traffic.',
      image: 'guideways/Fully_Dedicated_Fixed_Railway.jpg',
      quote: '“The train zips through some of the most congested roads. It took forever to build, though, and now local shop owners nearby complain that the tracks are cutting their customers off.”',
      costPerRevHour: 250,
      averageSpeed: 30,
      capitalCostPerMile: 80000000,
      maintenanceCosts: 20000000,
    }, {
      id: 2,
      title: 'Aerial Railway',
      desc: 'This guideway requires building new track above the street. The train will only stop at stations and can travel as fast as the track allows.',
      image: 'guideways/Aerial_Guideway.jpg',
      quote: '“I love how we don’t get stopped by traffic signals or stuck in traffic! Flying in the sky is fun and seems to be in keeping with Austin’s ‘weird’ vibe. Yet the neighbors are upset now that they have this ugly monstrosity looming over their homes and infringing on their privacy. You can forget sunbathing in your back yard!”',
      costPerRevHour: 250,
      averageSpeed: 40,
      capitalCostPerMile: 120000000,
      maintenanceCosts: 20000000,
    }],
  }, {
    id: 5,
    title: 'Heavy Rail (HRT)',
    disabled: true,
    desc: 'Heavy rail systems, like the New York City subway or Chicago “L”, require operation in their own space, separated from other transportation modes. This means that heavy rail systems, a form of high-capacity transit, must operate above and/or below street level. Some heavy rail systems were established over 100 years ago, when excavation and building costs were less expensive, and safety standards were different. Cities have grown up and expanded around these major projects over time.\n \n Today, heavy rail is one of the most expensive modes in the U.S. to build. Heavy rail’s benefits include speed, frequency and reliability, and the mode enjoys higher ridership than most other modes. Since heavy rail can move a lot of people, these systems are built in cities with the some of the largest populations in the country. \n \n We have fewer people living here than other major U.S. cities. Chicago and New York City, for instance, each have 5 to 10 times more people than Austin. To justify the high cost of building heavy rail, a city must have enough people to help balance the budget. Unfortunately, Austin must grow a lot before the return on this investment will make sense. Capital Metro is not studying heavy rail as a mode option for Project Connect.',
    image: 'modes/Heavy_Rail.jpg',
    capacityPerVehicle: 130,
    capitalCostPerVehicle: 7000000,
    minCapitalCostPerMile: 95000000,
    minMaintenanceCosts: 30000000,
    minAverageSpeed: 40,
    // guidewayChoices: [{
    //   id: 1,
    //   title: 'Fully Dedicated Fixed Railway',
    //   desc: 'This guideway requires building new track in the road. The train can travel without traffic however, the train will still need to yield to traffic signals along the route.',
    //   image: 'guideways/heavy_rail_fixed_dedicated_guideway.jpg',
    //   costPerRevHour: 300,
    //   averageSpeed: 40,
    //   capitalCostPerMile: 95000000,
    //   maintenanceCosts: 30000000,
    // }],
  }, {
    id: 6,
    title: 'Commuter Rail (DMU)',
    desc: 'A train operated in its own right of way to carry riders from the downtown core to stops throughout the region.',
    image: 'modes/Commuter_Rail.jpg',
    capacityPerVehicle: 120,
    capitalCostPerVehicle: 3000000,
    Frequency: '15 – 60 minutes',
    routeDistance: '15 – 30 miles',
    distanceBetweenStops: '1 – 5 miles',
    minCapitalCostPerMile: 20000000,
    minMaintenanceCosts: 10000000,
    minAverageSpeed: 35,
    quote: '“I really enjoy the cushy seats and being able to get work done but there aren’t enough stops. Plus, it seems like it’s just serving people living in the ‘burbs instead of Austinites. And it should serve city residents since we’re paying for it.”',
    guidewayChoices: [{
      id: 1,
      title: 'Fully Dedicated Fixed Railway',
      desc: 'This guideway requires building new track in the road. The train can travel without traffic however, the train will still need to yield to traffic signals along the route.',
      image: 'guideways/heavy_rail_fixed_dedicated_guideway.jpg',
      quote: '“The train zips through some of the most congested roads. It took forever to build, though, and now local shop owners nearby complain that the tracks are cutting their customers off.”',
      costPerRevHour: 120,
      averageSpeed: 35,
      capitalCostPerMile: 20000000,
      maintenanceCosts: 10000000,
    }],
  }, {
    id: 7,
    title: 'Gondola',
    disabled: true,
    desc: 'A recent proposal calls for building the largest and longest gondola system in the world right here in Austin. Gondolas are typically used for short trips (usually 1-2 miles) or in very difficult terrain where other transit modes struggle to provide service, like steep inclines or water crossings. Gondolas are also found in areas where a private developer has partnered (read: paid) to put the system in place. The Portland Aerial Tram and Oregon Health & Science University services were developed through partnerships, for example. Gondolas provide great views above the hustle-and-bustle of everyday life but cannot carry many people per car, don’t feature air conditioning, and typically move at the same pace as an average bicycle. For these reasons, this mode does not qualify for high-capacity transit investment. \n \n The Federal Transit Administration has never funded a gondola project. Furthermore, a recent study by the Texas A&M Transportation Institute revealed that gondola service, paid for solely by Capital Metro, is not a viable mode for the agency to add to their transit mix. Though gondolas certainly align with the “keep Austin weird” vibe, a private company or developer would have to fund gondolas in our city.',
    image: 'modes/Gondola.jpg',
    capacityPerVehicle: 12,
    capitalCostPerVehicle: 5000000,
    minCapitalCostPerMile: 55000000,
    minMaintenanceCosts: 20000000,
    minAverageSpeed: 8,
    // guidewayChoices: [{
    //   id: 1,
    //   title: 'Aerial Cable',
    //   desc: 'fixed guideway (rail); fully dedicated (median or curb)',
    //   image: 'guideways/gondola_old.jpg',
    //   costPerRevHour: 20,
    //   averageSpeed: 8,
    //   capitalCostPerMile: 55000000,
    //   maintenanceCosts: 20000000,
    // }],
  },
]

export default modeChoices;
