const modeChoices = [
  {
    id: 1,
    title: 'Rapid Bus',
    desc: 'Snackwave tbh ennui, squid jianbing lyft XOXO. Hoodie woke iPhone, etsy roof party locavore tote bag microdosing retro authentic raclette hammock venmo 90\'s.',
    image: 'modes/rapid_bus.jpg',
    capacityPerVehicle: 50,
    capitalCostPerVehicle: 700000,
    guidewayChoices: [{
      id: 1,
      title: 'Mixed with Normal Traffic',
      desc: 'Snackwave tbh ennui, squid jianbing lyft XOXO. Hoodie woke iPhone, etsy roof party locavore tote bag microdosing retro authentic raclette hammock venmo 90',
      image: 'modes/rapid_bus.jpg',
      costPerRevHour: 60,
      averageSpeed: 15,
      capitalCostPerMile: 700000,
      maintenanceCosts: 2500000,
    }],
  }, {
    id: 2,
    title: 'Bus Rapid Transit',
    desc: 'Launched in 2014 as MetroRapid, bus rapid transit (BRT) offers more frequent service with more amenities, like free onboard Wi-Fi, providing an attractive alternative to driving cars. It operates in mixed traffic or in transit-only lanes through downtown on Guadalupe and Lavaca Streets between MLK and Cesar Chavez. Special technology allows MetroRapid vehicles to catch more green lights to stay on schedule.',
    image: 'modes/bus_rapid_transit.jpg',
    capacityPerVehicle: 50,
    capitalCostPerVehicle: 700000,
    guidewayChoices: [{
      id: 1,
      title: 'Mixed with Normal Traffic',
      desc: 'Snackwave tbh ennui, squid jianbing lyft XOXO. Hoodie woke iPhone, etsy roof party locavore tote bag microdosing retro authentic raclette hammock venmo 90',
      image: 'modes/rapid_bus.jpg',
      costPerRevHour: 60,
      averageSpeed: 20,
      capitalCostPerMile: 2500000,
      maintenanceCosts: 2500000,
    }, {
      id: 2,
      title: 'Fully Dedicated Lane',
      desc: 'Snackwave tbh ennui, squid jianbing lyft XOXO. Hoodie woke iPhone, etsy roof party locavore tote bag microdosing retro authentic raclette hammock venmo 90',
      image: 'modes/rapid_bus.jpg',
      costPerRevHour: 70,
      averageSpeed: 35,
      capitalCostPerMile: 9000000,
      maintenanceCosts: 2500000,
    }],
  }, {
    id: 3,
    title: 'Modern Streetcar',
    desc: 'Unlike light-rail or heavy-rail systems, which tend to focus on serving a larger number of passengers over longer distances, the modern streetcar vehicle is smaller and typically runs a length of 3 to 5 miles. Due to its scale, the modern streetcar is more pedestrian- and cyclist-friendly, the implementation cost is considerably lower, and the required infrastructure can more easily be implemented on regular streets.',
    image: 'modes/modern_streetcar.jpg',
    capacityPerVehicle: 90,
    capitalCostPerVehicle: 3500000,
    guidewayChoices: [{
      id: 1,
      title: 'Fixed Rail with Mixed Traffic',
      desc: 'fixed guideway (rails); no dedication',
      image: 'modes/rapid_bus.jpg',
      costPerRevHour: 180,
      averageSpeed: 8,
      capitalCostPerMile: 15000000,
      maintenanceCosts: 25000000,
    }, {
      id: 2,
      title: 'Fully Dedicated Fixed Railway',
      desc: 'fixed guideway (rail); fully dedicated (median or curb)',
      image: 'modes/rapid_bus.jpg',
      costPerRevHour: 180,
      averageSpeed: 12,
      capitalCostPerMile: 25000000,
      maintenanceCosts: 25000000,
    }],
  }, {
    id: 4,
    title: 'Light Rail (LRT)',
    desc: 'The primary advantage of light-rail transit is its adaptability, both in terms of the variety of environments it can operate in and its ability to add passenger capacity. Light rail is mostly operated in denser, more centralized, more walkable areas of a city where there is no free parking. Light rail can operate and cross roadways at street level mainly along dedicated rights-of-way, or it can operate in a totally separate guideway, either elevated or underground. Light rail can also quickly add passenger capacity, accommodating up to 10 times the number of riders as a bus.',
    image: 'modes/light_rail.jpg',
    capacityPerVehicle: 110,
    capitalCostPerVehicle: 5000000,
    guidewayChoices: [{
      id: 1,
      title: 'Fixed Dedicated Guideway',
      desc: 'fixed guideway (rail); fully dedicated (median or curb)',
      image: 'modes/rapid_bus.jpg',
      costPerRevHour: 250,
      averageSpeed: 30,
      capitalCostPerMile: 25000000,
      maintenanceCosts: 20000000,
    }, {
      id: 2,
      title: 'Aerial Railway',
      desc: 'fixed guideway (rail); fully dedicated (median or curb)',
      image: 'modes/rapid_bus.jpg',
      costPerRevHour: 250,
      averageSpeed: 40,
      capitalCostPerMile: 45000000,
      maintenanceCosts: 20000000,
    }],
  }, {
    id: 5,
    title: 'Heavy Rail (HRT)',
    desc: 'Ugh messenger bag 90\'s, everyday carry street art bicycle rights post-ironic photo booth chartreuse authentic single-origin coffee sustainable.',
    image: 'modes/heavy_rail.jpg',
    capacityPerVehicle: 130,
    capitalCostPerVehicle: 7000000,
    guidewayChoices: [{
      id: 1,
      title: 'Fixed Dedicated Guideway',
      desc: 'fixed guideway (rail); fully dedicated (median or curb)',
      image: 'modes/rapid_bus.jpg',
      costPerRevHour: 300,
      averageSpeed: 40,
      capitalCostPerMile: 95000000,
      maintenanceCosts: 30000000,
    }],
  }, {
    id: 6,
    title: 'Commuter Rail (DMU)',
    desc: 'MetroRail is already operating the 32-mile Red Line commuter rail service with 9 stations between Leander and downtown Austin with trains at capacity during rush hours. Commuter Rail can carry 400 - 1,400 passengers during rush hour and travels at an average speed of 30-50 mph. Rail stops are between 1 - 5 miles apart.',
    image: 'modes/commuter_rail.jpg',
    capacityPerVehicle: 120,
    capitalCostPerVehicle: 3000000,
    guidewayChoices: [{
      id: 1,
      title: 'Fixed Dedicated Guideway',
      desc: 'fixed guideway (rail); fully dedicated (median or curb)',
      image: 'modes/rapid_bus.jpg',
      costPerRevHour: 120,
      averageSpeed: 35,
      capitalCostPerMile: 20000000,
      maintenanceCosts: 10000000,
    }],
  }, {
    id: 7,
    title: 'Gondola',
    desc: 'You probably haven\'t heard of them paleo hot chicken trust fund affogato.',
    image: 'modes/gondola.jpg',
    capacityPerVehicle: 12,
    capitalCostPerVehicle: 5000000,
    guidewayChoices: [{
      id: 1,
      title: 'Aerial Cable',
      desc: 'fixed guideway (rail); fully dedicated (median or curb)',
      image: 'modes/rapid_bus.jpg',
      costPerRevHour: 20,
      averageSpeed: 8,
      capitalCostPerMile: 55000000,
      maintenanceCosts: 20000000,
    }],
  },
]

export default modeChoices;
