const modeChoices = [
  {
    id: 1,
    disabled: true,
    title: 'Rapid Bus',
    desc: 'Rapid bus, like MetroRapid, offers more frequent service with more amenities, like free onboard Wi-Fi. Rapid bus does not have enough dedicated space to operate as true high-capacity transit.',
    image: 'modes/Rapid_Bus.jpg',
    capitalCostPerVehicle: 700000,
    minCapitalCostPerMile: 700000,
    minMaintenanceCosts: 2500000,
    capacityPerVehicle: 50,
    // guidewayChoices: [{
    //   id: 1,
    //   title: 'Mixed with Normal Traffic',
    //   desc: 'This guideway is the least expensive to construct because it requires few changes. This solution is only as fast as the rest of traffic.',
    //   image: 'guideways/Mixed_with_Normal_Traffic.jpg',
    //   costPerRevHour: 60,
    //   averageSpeed: 15,
    //   capitalCostPerMile: 700000,
    //   maintenanceCosts: 2500000,
    // }],
  }, {
    id: 2,
    title: 'Bus Rapid Transit',
    desc: 'Bus routes that operate in either mixed traffic or their own lanes and provide faster service to connect local activity centers.',
    image: 'modes/Bus_Rapid_Transit.jpg',
    capacityPerVehicle: 60,
    frequency: '10 – 30 minutes',
    routeDistance: '5 – 15 miles',
    distanceBetweenStops: '1/2 – 2 miles',
    capitalCostPerVehicle: 700000,
    minCapitalCostPerMile: 2500000,
    minMaintenanceCosts: 2500000,
    guidewayChoices: [{
      id: 1,
      title: 'Mixed with Normal Traffic',
      desc: 'This guideway is the least expensive to construct because it requires few changes. This solution is only as fast as the rest of traffic.',
      image: 'guideways/Mixed_with_Normal_Traffic.jpg',
      costPerRevHour: 60,
      averageSpeed: 15,
      capitalCostPerMile: 2500000,
      maintenanceCosts: 2500000,
    }, {
      id: 2,
      title: 'Dedicated Lane',
      desc: 'This guideway converts a lane for cars into a transit-only lane. – A little paint and now your transit solution is free from traffic!',
      image: 'guideways/Bus_Rapid_Transit_on_Highway.jpg',
      costPerRevHour: 70,
      averageSpeed: 35,
      capitalCostPerMile: 9000000,
      maintenanceCosts: 2500000,
    }],
  }, {
    id: 3,
    title: 'Modern Streetcar',
    desc: 'Electrified rail service that can operate either in mixed traffic or in its own lane. This service is typically used to circulate in dense, urban areas.',
    image: 'modes/Modern_Streetcar.jpg',
    capacityPerVehicle: 90,
    capitalCostPerVehicle: 3500000,
    frequency: '5 – 15 minutes',
    routeDistance: '2 – 5 miles',
    distanceBetweenStops: '1/8 mile – 1/2 mile',
    minCapitalCostPerMile: 15000000,
    minMaintenanceCosts: 25000000,
    guidewayChoices: [{
      id: 1,
      title: 'Fixed Rail with Mixed Traffic',
      desc: 'This guideway requires building new track in the road. Because cars can still drive in the same lane as the train, the train is only as fast as the rest of traffic.',
      image: 'guideways/Fixed_Rail_with_Mixed_Traffic.jpg',
      costPerRevHour: 180,
      averageSpeed: 15,
      capitalCostPerMile: 15000000,
      maintenanceCosts: 25000000,
    }, {
      id: 2,
      title: 'Fully Dedicated Fixed Railway',
      desc: 'This guideway requires building new track in the road. The train can travel without traffic however, the train will still need to yield to traffic signals along the route.',
      image: 'guideways/Fully_Dedicated_Fixed_Railway.jpg',
      costPerRevHour: 180,
      averageSpeed: 30,
      capitalCostPerMile: 25000000,
      maintenanceCosts: 25000000,
    }],
  }, {
    id: 4,
    title: 'Light Rail (LRT)',
    desc: 'Electrified rail service that operates in its own lane (or right of way), and connects local activity centers.',
    image: 'modes/Light_Rail.jpg',
    capacityPerVehicle: 110,
    frequency: '10 – 30 minutes',
    routeDistance: '5 – 15 miles',
    distanceBetweenStops: '1/2 – 2 miles',
    capitalCostPerVehicle: 5000000,
    minCapitalCostPerMile: 25000000,
    minMaintenanceCosts: 20000000,
    guidewayChoices: [{
      id: 1,
      title: 'Fully Dedicated Fixed Railway',
      desc: 'This guideway requires building new track in the road. Because cars can still drive in the same lane as the train, the train is only as fast as the rest of traffic.',
      image: 'guideways/Fully_Dedicated_Fixed_Railway.jpg',
      costPerRevHour: 250,
      averageSpeed: 30,
      capitalCostPerMile: 25000000,
      maintenanceCosts: 20000000,
    }, {
      id: 2,
      title: 'Aerial Railway',
      desc: 'This guideway requires building new track above the street. The train will only stop at stations and can travel as fast as the track allows.',
      image: 'guideways/Aerial_Guideway.jpg',
      costPerRevHour: 250,
      averageSpeed: 40,
      capitalCostPerMile: 45000000,
      maintenanceCosts: 20000000,
    }],
  }, {
    id: 5,
    title: 'Heavy Rail (HRT)',
    disabled: true,
    desc: 'Heavy rail operates in very dense cities such as New York and London. Operating and capital costs are among the highest of the modes and currently Austin does not have the density or funds to pay for a system.',
    image: 'modes/Heavy_Rail.jpg',
    capacityPerVehicle: 130,
    capitalCostPerVehicle: 7000000,
    minCapitalCostPerMile: 95000000,
    minMaintenanceCosts: 30000000,
    // guidewayChoices: [{
    //   id: 1,
    //   title: 'Fully Dedicated Fixed Railway',
    //   desc: 'This guideway requires building new track in the road. The train can travel without traffic however, the train will still need to yield to traffic signals along the route.',
    //   image: 'guideways/heavy_rail_fixed_dedicated_guideway.jpg',
    //   costPerRevHour: 300,
    //   averageSpeed: 40,
    //   capitalCostPerMile: 95000000,
    //   maintenanceCosts: 30000000,
    // }],
  }, {
    id: 6,
    title: 'Commuter Rail (DMU)',
    desc: 'A train operated in its right of way to carry riders from the downtown core to stops throughout the region.',
    image: 'modes/Commuter_Rail.png',
    capacityPerVehicle: 120,
    capitalCostPerVehicle: 3000000,
    Frequency: '15 – 60 minutes',
    routeDistance: '15 – 30 miles',
    distanceBetweenStops: '1 – 5 miles',
    minCapitalCostPerMile: 20000000,
    minMaintenanceCosts: 10000000,
    guidewayChoices: [{
      id: 1,
      title: 'Fully Dedicated Fixed Railway',
      desc: 'This guideway requires building new track in the road. The train can travel without traffic however, the train will still need to yield to traffic signals along the route.',
      image: 'guideways/heavy_rail_fixed_dedicated_guideway.jpg',
      costPerRevHour: 120,
      averageSpeed: 35,
      capitalCostPerMile: 20000000,
      maintenanceCosts: 10000000,
    }],
  }, {
    id: 7,
    title: 'Gondola',
    disabled: true,
    desc: 'Gondola cable car systems are used for short trips in extreme environments with challenges that prevent typical high-capacity transit solutions.',
    image: 'modes/Gondola.jpg',
    capacityPerVehicle: 12,
    capitalCostPerVehicle: 5000000,
    minCapitalCostPerMile: 55000000,
    minMaintenanceCosts: 20000000,
    // guidewayChoices: [{
    //   id: 1,
    //   title: 'Aerial Cable',
    //   desc: 'fixed guideway (rail); fully dedicated (median or curb)',
    //   image: 'guideways/gondola_old.jpg',
    //   costPerRevHour: 20,
    //   averageSpeed: 8,
    //   capitalCostPerMile: 55000000,
    //   maintenanceCosts: 20000000,
    // }],
  },
]

export default modeChoices;
